### ISSUE TITLE
update requests fail with 500 Internal Server Error

### ISSUE THREAD

**Issue by cweiske** [kylewm/silo.pub#35]
I wanted to add some text to the github comment https://github.com/kylewm/silo.pub/issues/34#issuecomment-247249551 with [shpub](https://github.com/cweiske/shpub).

That fails:
```
$ shpub-0.0.6.phar -s github update https://github.com/kylewm/silo.pub/issues/34#issuecomment-247249551\
    --add 'content=commented with shpub'
Server returned an error status code 500
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Equivalent curl request:
```
curl -X POST-H 'Content-Type: application/json' -H 'Authorization: Bearer abc'\
    --data '{"action":"update","url":"https:\/\/github.com\/kylewm\/silo.pub\/issues\/34#issuecomment-247249551","add":{"content":["commented with shpub"]}}'\
    'https://silo.pub/micropub'
```

**Comment by kylewm** [comment]
```
Exception on /micropub [POST]
Traceback (most recent call last):
  File "/srv/www/silo.pub/silopub/venv/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/www/silo.pub/silopub/venv/lib/python3.4/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/srv/www/silo.pub/silopub/venv/lib/python3.4/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```
